language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
jobs:
    - arch: arm64
      python: 3.7
branches:
  only:
  - master

notifications:
  email:
    recipients:
    - zeek-commits-internal@zeek.org

before_install: pip install btest

install: python setup.py install

script: make test BTEST=`which btest`

after_failure: cat testing/diag.log
